sudo: false

dist: focal

env:
  - CXX=g++
  - CXX=clang++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

language: node_js

os:
  - linux
  - osx

osx_image: xcode13.2

node_js:
  - "10"
  - "12"
  - "14"
  - "16"

jobs:
  include:
      - os: linux
        arch: arm64
        node_js: 16
        env: CXX=g++
  exclude:
      - os: osx
        env: CXX=g++
      - os: linux
        env: CXX=clang++

install:
  - npm install --build-from-source --no-package-lock

after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

before_deploy: |-
  ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
  npm run prebuild --v8_enable_pointer_compression=false --v8_enable_31bit_smis_on_64bit_arch=false
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    ARCH=ia32 npm run prebuild --v8_enable_pointer_compression=false --v8_enable_31bit_smis_on_64bit_arch=false
  fi
  tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    rm -fr "$TRAVIS_BUILD_DIR/prebuilds"
    ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-arm64.tar"
    PREBUILD_ARCH=arm64 npm run prebuild --v8_enable_pointer_compression=false --v8_enable_31bit_smis_on_64bit_arch=false
    tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .
  fi

deploy:
  provider: releases
  draft: false
  prerelease: true
  file_glob: true
  file: "*.tar"
  skip_cleanup: true
  on:
    tags: true
    node: 16
  api_key: $PREBUILD_GITHUB_TOKEN
